package release

import (
	"context"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/joshsukhdeo/gh-pt/safety"
	"github.com/joshsukhdeo/gh-pt/selector"
	"github.com/joshsukhdeo/gh-pt/state"
)

// SetupBinaryCompletions checks an installed binary for completion generation
// or extracts completion scripts, saving them to $XDG_DATA_HOME/gh-pt/completions/.
func SetupBinaryCompletions(binaryPath string, noCompletionSetup bool) error {
	if safety.IsDryRun() || noCompletionSetup || binaryPath == "" {
		return nil
	}

	binName := filepath.Base(binaryPath)
	dataHome := state.GetDataHome()
	compBaseDir := filepath.Join(dataHome, "gh-pt", "completions")
	bashDir := filepath.Join(compBaseDir, "bash")
	zshDir := filepath.Join(compBaseDir, "zsh")

	_ = os.MkdirAll(bashDir, 0755)
	_ = os.MkdirAll(zshDir, 0755)

	// Try probing binary for completion output (e.g. `bin completion bash`)
	probedBash := probeAndSaveCompletion(binaryPath, binName, "bash", filepath.Join(bashDir, binName))
	probedZsh := probeAndSaveCompletion(binaryPath, binName, "zsh", filepath.Join(zshDir, "_"+binName))

	if probedBash || probedZsh {
		updateCompletionLoaders(compBaseDir)
	}

	return nil
}

// ScanAndInstallArchiveCompletions sweeps an extracted directory for completion scripts
// (e.g. complete.bash, <bin>.bash, <bin>.zsh, completions/*) and copies them to the completions store.
func ScanAndInstallArchiveCompletions(archiveDir, binName string, noCompletionSetup bool) bool {
	if safety.IsDryRun() || noCompletionSetup || archiveDir == "" || binName == "" {
		return false
	}

	dataHome := state.GetDataHome()
	compBaseDir := filepath.Join(dataHome, "gh-pt", "completions")
	bashDir := filepath.Join(compBaseDir, "bash")
	zshDir := filepath.Join(compBaseDir, "zsh")

	installed := false

	_ = filepath.WalkDir(archiveDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil
		}
		name := strings.ToLower(d.Name())
		lowerBin := strings.ToLower(binName)
		slashPath := filepath.ToSlash(strings.ToLower(path))

		// Check bash completions
		if name == "complete.bash" || name == lowerBin+".bash" || name == "bash_completion" ||
			(strings.Contains(slashPath, "completions/bash") && (name == lowerBin || strings.HasPrefix(name, lowerBin))) ||
			(strings.HasSuffix(name, ".bash") && strings.Contains(name, lowerBin)) {
			_ = os.MkdirAll(bashDir, 0755)
			dest := filepath.Join(bashDir, binName)
			if copyFile(path, dest, 0644) == nil {
				installed = true
			}
		}

		// Check zsh completions
		if name == lowerBin+".zsh" || name == "_"+lowerBin ||
			(strings.Contains(slashPath, "completions/zsh") && (name == "_"+lowerBin || strings.HasPrefix(name, "_"+lowerBin))) ||
			(strings.HasSuffix(name, ".zsh") && strings.Contains(name, lowerBin)) {
			_ = os.MkdirAll(zshDir, 0755)
			dest := filepath.Join(zshDir, "_"+binName)
			if copyFile(path, dest, 0644) == nil {
				installed = true
			}
		}

		return nil
	})

	if installed {
		updateCompletionLoaders(compBaseDir)
	}
	return installed
}

// probeAndSaveCompletion tests common completion CLI subcommands with a short timeout.
func probeAndSaveCompletion(binaryPath, binName, shell, destPath string) bool {
	ctx, cancel := context.WithTimeout(context.Background(), 750*time.Millisecond)
	defer cancel()

	candidates := [][]string{
		{"completion", shell},
		{"completions", shell},
		{"--completion", shell},
		{"--completions", shell},
	}

	for _, args := range candidates {
		cmd := exec.CommandContext(ctx, binaryPath, args...)
		out, err := cmd.Output()
		if err == nil && len(out) > 50 {
			outStr := string(out)
			// Validate output looks like shell code
			if strings.Contains(outStr, "complete") || strings.Contains(outStr, "compdef") || strings.Contains(outStr, "#!/") {
				if err := os.WriteFile(destPath, out, 0644); err == nil {
					return true
				}
			}
		}
	}
	return false
}

// updateCompletionLoaders updates gh-pt-completions.bash and gh-pt-completions.zsh
// beside state.json to allow users to source a single master file.
func updateCompletionLoaders(compBaseDir string) {
	dataHome := state.GetDataHome()
	ghPtDir := filepath.Join(dataHome, "gh-pt")

	bashLoader := filepath.Join(ghPtDir, "completions.bash")
	zshLoader := filepath.Join(ghPtDir, "completions.zsh")

	bashScript := fmt.Sprintf(`# gh-pt autogenerated completions loader
for comp in %s/*; do
	[ -f "$comp" ] && . "$comp"
done
`, filepath.Join(compBaseDir, "bash"))

	zshScript := fmt.Sprintf(`# gh-pt autogenerated zsh completions loader
fpath=(%s $fpath)
for comp in %s/*(N); do
	[ -f "$comp" ] && source "$comp"
done
`, filepath.Join(compBaseDir, "zsh"), filepath.Join(compBaseDir, "zsh"))

	_ = os.WriteFile(bashLoader, []byte(bashScript), 0644)
	_ = os.WriteFile(zshLoader, []byte(zshScript), 0644)
}

// IsAllowedBinaryDir checks if a file inside an archive sits in root, bin, bin32, or bin64.
func IsAllowedBinaryDir(relPath string) bool {
	return selector.IsAllowedBinaryDir(relPath)
}
